### ISSUE TITLE
testing live version

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#98] opened 2015-02-16 21:24 UTC
It looks like we are getting close. We need to test the live version - i.e.

@sapi's initial testing:
- [x] Test that `mpt_installer.py` works correctly
- [x] Update MyPyTutor itself, and test that the client automatically updates
- [x] Update the tutorial set, and test that the client automatically downloads the updates

Verification by someone else:
- [ ] Test that `mpt_installer.py` works correctly
- [ ] Update MyPyTutor itself, and test that the client automatically updates
- [ ] Update the tutorial set, and test that the client automatically downloads the updates

**Comment by sapi** [comment] 2015-02-24 11:03
@pjritee Could you please verify that the installer, client updates, and tutorial set updates work for you?

You can verify the installer by installing.

You can verify client updates by uploading a newer version of the client (determined by the `VERSION` module attribute in `tutorlib.gui.app.app`).

You can verify tutorial set updates by changing a tutorial problem and running `make push`.

**Comment by pjritee** [comment] 2015-02-24 22:45
The installer runs OK - it would be good that if the OS is Linux or OSX then it sets permissions to be executable.

I get

$ ls
CSSE1001Answers  CSSE1001Problems  MyPyTutor.py  MyPyTutor.pyw  tutorlib
$ ls CSSE1001Problems
add_functions.tut  gui1.tut           list1.tut              sqfun.tut
assignments.tut    gui2.tut           list2.tut              string1.tut
class_point.tut    gui3.tut           list3.tut              string2.tut
class_rect.tut     if1.tut            list4.tut              string3.tut
class_use.tut      if2.tut            list_comp.tut          string4.tut
config.txt         if3.tut            meanfun.tut            string5.tut
dict1.tut          inherit_calls.tut  range.tut              string6.tut
dict2.tut          inherit_def.tut    recursion_add.tut      stringtuple.tut
dict3.tut          intro.tut          recursion_digits.tut   tuple.tut
dict4.tut          lambda.tut         recursion_list.tut     tutorials.txt
except1.tut        layout1.gif        recursive_digits2.tut  whilebreak.tut
except2.tut        layout2.gif        recursive_digits3.tut  whileif.tut
fun1.tut           layout3.gif        repeated_apply.tut     while.tut
$ 
$ python3 MyPyTutor.py 
Traceback (most recent call last):
  File "MyPyTutor.py", line 27, in <module>
    from tutorlib.gui.app.app import TutorialApp, VERSION
  File "/home/pjr/research/MyPyTutor3/test/tutorlib/gui/app/app.py", line 7, in <module>
    from tutorlib.config.attempts import TutorialAttempts
  File "/home/pjr/research/MyPyTutor3/test/tutorlib/config/attempts.py", line 4, in <module>
    from tutorlib.config.shared import TUTORIAL_ATTEMPTS_FILE
  File "/home/pjr/research/MyPyTutor3/test/tutorlib/config/shared.py", line 9, in <module>
    '{} should be a directory.  Please delete the existing config '
AssertionError: {} should be a directory.  Please delete the existing config 


We also need to test that if the tutorials change then an auto update  automatically happens and
ditto for a change of the MPT code (i.e. version number)

**Comment by pjritee** [comment] 2015-02-24 22:47
Oh - and the how to install MPT page on the course web page needs updating - really that page should move to the MPT pages and simply linked to from the course web page

**Comment by sapi** [comment] 2015-02-24 22:48
The assertion error is just for us; I changed to a config directory, but with the same name as the old config file. Once you remove (or move) the old file it'll work fine. 

Permissions would be good, but I might wait for time to rewrite the installer properly. I'm just using your old one at the moment.

**Comment by pjritee** [comment] 2015-02-24 22:51
Which config file? There is a config.txt in the problems directory???

**Comment by sapi** [comment] 2015-02-24 22:53
Should be ~/.mptrc

Looks like I forgot to provide that as an argument to the format strong, my
mistake.

**Comment by pjritee** [comment] 2015-02-24 22:59
$ python3 MyPyTutor.py 
Traceback (most recent call last):
  File "MyPyTutor.py", line 86, in <module>
    main()
  File "MyPyTutor.py", line 81, in main
    TutorialApp(root)
  File "/home/pjr/research/MyPyTutor3/test/tutorlib/gui/app/app.py", line 92, in __init__
    self.attempts = TutorialAttempts()
TypeError: __init__() missing 1 required positional argument: 'tutorial_package'

**Comment by sapi** [comment] 2015-02-24 23:04
Do you have the latest version? My local version runs fine, but it's
possible that I forgot to push. Unfortunately I'm not going to be in front
of my computer today to fix it, sorry. I'll push again (if that's what the
problem is) tonight.

**Comment by pjritee** [comment] 2015-02-24 23:09
I did a pull before trying

**Comment by sapi** [comment] 2015-02-24 23:13
The latest version of the zip file I have in Dropbox is
https://www.dropbox.com/s/tzwunb925nwcnfa/mypytutor34.zip?dl=0

That may be the latest version (without git though, as it's the student
version) and so it may allow you to test. Otherwise I'm just going to have
to push later, sorry. I don't have my private key on my phone so I can't
ssh in anywhere to do the push remotely.

**Comment by pjritee** [comment] 2015-02-24 23:31
I get the same error when I unziped your code

**Comment by sapi** [comment] 2015-02-24 23:34
I must have forgotten to make and push (or removed the internet before it
was done), sorry. The version in my Dropbox is fine, so I'll push that as
soon as I can (probably tonight).

You may be able to download a sip of my working directory from here, but
that's the best I can do off my mobile:
https://www.dropbox.com/sh/l47hrc24g59qtoc/AAD8Vc1icS4_z_1qQVMspoTla?dl=0

**Comment by pjritee** [comment] 2015-02-24 23:36
You have in config/attempts.py
class TutorialAttempts():
(should that have object as an arg or is that not needed in P3?)
but you have on line 19:
    def __init__(self, tutorial_package, path=TUTORIAL_ATTEMPTS_FILE):
but in app you have
self.attempts = TutorialAttempts()

**Comment by sapi** [comment] 2015-02-24 23:37
attempts.py is out of date for some reason. My version doesn't (and
shouldn't) need a tutorial package argument.

**Comment by sapi** [comment] 2015-02-25 07:40
I checked just now; both my local working copy and the repo are in sync, and there's no issues running my working copy.  It must be something on your end (perhaps on the wrong branch, or out of date in some other way?)

**Comment by pjritee** [comment] 2015-02-25 20:24
OK - the installer runs and MPT starts up with both a login window and the window to choose Problem and Answer dirs and after that I get an error box with 
Failed to load tutorial problems:
Failed to parse tutorial file

**Comment by sapi** [comment] 2015-02-25 20:28
I forgot to fix where the installer put the config file when I changed to
using a directory. Good catch.

**Comment by starsnabove** [comment] 2015-02-25 21:33
On windows 7 installs fine and logs in and selects the choose problem/answer dirs fine but then get the Falis to parse tutorial file (same as peter) accompanied with the following error when press OK.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 582, in callit
    func(*args)
  File "C:\Users\starsnabove\Downloads\mpt\tutorlib\gui\app\app.py", li
n update_submissions
    submissions = self.web_api.get_submissions(self.tutorial_package)
  File "C:\Users\starsnabove\Downloads\mpt\tutorlib\interface\web_api.p
537, in get_submissions
    return self._parse_submissions(response, tutorial_package)
  File "C:\Users\starsnabove\Downloads\mpt\tutorlib\interface\web_api.p
582, in _parse_submissions
    tutorial = tutorial_package.tutorial_with_hash(tutorial_hash)
AttributeError: 'NoneType' object has no attribute 'tutorial_with_hash'


I also get the following when I close the program

Exception ignored in: <bound method Interpreter.__del__ of <tutorlib.interface
nterpreter.Interpreter object at 0x030367B0>>
Traceback (most recent call last):
  File "C:\Users\starsnabove\Downloads\mpt\tutorlib\interface\interpreter.py",
ine 37, in __del__
PermissionError: [WinError 32] The process cannot access the file because it i
being used by another process: 'C:\\Users\\STARSN~1\\AppData\\Local\\Temp\\tmp
i42dt0'
Exception ignored in: <bound method MultiCall.__del__ of <idlelib.MultiCall.Mu
iCallCreator.<locals>.MultiCall object at 0x033F14B0>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 413, in __del__
  File "C:\Python34\lib\idlelib\MultiCall.py", line 102, in unbind
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _SimpleBinder.__del__ of <idlelib.MultiCal
_SimpleBinder object at 0x034031D0>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 109, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _SimpleBinder.__del__ of <idlelib.MultiCal
_SimpleBinder object at 0x03403250>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 109, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCa
._ComplexBinder object at 0x03403530>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 244, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCa
._ComplexBinder object at 0x033F1E50>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 244, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCa
._ComplexBinder object at 0x033F15B0>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 244, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
Exception ignored in: <bound method _ComplexBinder.__del__ of <idlelib.MultiCa
._ComplexBinder object at 0x033F1590>>
Traceback (most recent call last):
  File "C:\Python34\lib\idlelib\MultiCall.py", line 244, in __del__
  File "C:\Python34\lib\tkinter\__init__.py", line 1092, in unbind
_tkinter.TclError: can't invoke "bind" command: application has been destroyed

**Comment by starsnabove** [comment] 2015-02-25 22:00
On Windows 8

It immediately shows the "Login Failed" window stating "Please check your credentials and try again. If the problem persists ...."
 
Again got "Falied to parse tutorials file" but no exception on "OK"
Tried to login - does not show login screen just same error window
When closed got the following error

**Comment by sapi** [comment] 2015-02-25 22:56
I fixed that bug; MPT was installing the incorrect tutorial problems.

Could you both please check if that has resolved the issue on your end?  You should probably do a clean install, including deleting the config directory.

I might also clean up the installer this morning.

**Comment by pjritee** [comment] 2015-02-25 23:06
Nope:

$ code/mpt_installer.py 
Traceback (most recent call last):
  File "code/mpt_installer.py", line 290, in <module>
    main()
  File "code/mpt_installer.py", line 286, in main
    Installer(root)
  File "code/mpt_installer.py", line 128, in __init__
    self.run_installer()
  File "code/mpt_installer.py", line 225, in run_installer
    unzipfile('CSSE1001Tutorials.zip', tutorial_dir)
  File "code/mpt_installer.py", line 54, in unzipfile
    return zf.extractall(path)
  File "/usr/lib/python3.4/zipfile.py", line 1240, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python3.4/zipfile.py", line 1228, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.4/zipfile.py", line 1291, in _extract_member
    open(targetpath, "wb") as target:
NotADirectoryError: [Errno 20] Not a directory: '/home/pjr/research/MyPyTutor3/MPT34/CSSE1001Problems/add_functions.tut/analysis.py'


Ah - actually after removing the contents of MPT34 and trying again it's OK (but MPT is not set to executable)

**Comment by pjritee** [comment] 2015-02-25 23:14
We now need to test that the problems and MPT do an auto update. What's the simplest way to do that?

**Comment by sapi** [comment] 2015-02-25 23:19
To test both, you'll need a copy of MPT outside the git working directory (so that it's not seeing the files you change as you do this).  The copy you get from running the installer would be good.

For the tutorial problems, change something (try to make it something useful anyway, like fixing a typo or the like), run `make push`, load MPT, and check the change has been synced.  (There's no message; it just does it.)

For MPT itself, make a change, change the `VERSION` number in `tutorlib.gui.app.app` to something higher, and re-run MPT.

I'm working on a bootstrap script which makes these two a little bit cleaner from a design perspective, but it shouldn't change anything functional, so testing now should be ok.

**Comment by pjritee** [comment] 2015-02-25 23:54
I changed the version number in tutorlib/gui/app/app.py to 2.0.0 and started MPT and it seemed to overwrite that file and reload - so that seems OK.
Is there a similar trick I can do for the tutorials or is that too complicated and I should try the suggested approach?

**Comment by sapi** [comment] 2015-02-25 23:56
You can change the number in `CSSE1001Tutorials/config.txt` (NB: the one in the MyPyTutor dir, not the working dir) to an earlier number.  That should trigger an update.

**Comment by pjritee** [comment] 2015-02-26 00:00
Yes that seemed to work - it's all silent though - the old version popped up a window when something changed - would that be a good idea or not???

**Comment by sapi** [comment] 2015-02-26 00:00
I'm going to work that into the bootstrap script.  Probably just text based though, to reduce the number of popup windows for the students.

**Comment by pjritee** [comment] 2015-02-26 00:02
So would that text appear in the status area?  Or on the welcome screen?

**Comment by sapi** [comment] 2015-02-26 00:03
I was considering in the terminal window?  It's not that important to students; it's more for our own troubleshooting.

**Comment by pjritee** [comment] 2015-02-26 00:06
Ah - I see. I guess I was asking if it was important to students. The downside of showing something has changed is that it might freak out some students. The upside is it might show students we are responding with fixes. I'm not sure either way

**Comment by starsnabove** [comment] 2015-02-26 00:24
In Windows 8

I still cannot log on. When I go to online/logon it just shows the same window stating that my credentials are incorrect, not the logon window.

Also if I go to open the interpreter I get the following exception

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\gui\app\menu.py", line 179,
in <lambda>
    callback = (lambda n=cb_name: lambda evt=None: self.callback(n))()
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\gui\app\menu.py", line 210,
in callback
    return method()
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\gui\app\menu.py", line 331,
in menu_tools_interpreter
    self.delegate.show_interpreter()
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\gui\utils\decorators.py", li
ne 10, in method
    return f(self, *args, **kwargs)
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\gui\app\app.py", line 787, i
n show_interpreter
    self.interpreter.reload(self.editor.get_text())
  File "c:\Users\Starsnabove\Documents\mpt\tutorlib\interface\interpreter.py", l
ine 92, in reload
    self.subprocess = Popen(self.args)
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by sapi** [comment] 2015-02-26 00:32
I can reproduce the interpreter bug: see #120

I cannot reproduce the login error, either initially or by cancelling out of the first login menu and then going Online -> Login.  What exact steps are you going through?  I really hope we don't have a Win8 specific bug :(

**Comment by starsnabove** [comment] 2015-02-26 00:34
Updating using the same methods as @pjritee seems to work on windows 8

**Comment by starsnabove** [comment] 2015-02-26 00:38
The message appears when I first open the program and whenever I try to do Online -> Login.

It seems to occur whenever it attempts to create the login window to put user details in, but I do not get that window at all. There are no exceptions in the terminal either

**Comment by sapi** [comment] 2015-02-26 00:39
Can you grep for the error string you're seeing in the message box, and put a `raise` (not `raise e`) directly above it?  (I assume it will be in an exception handler.  If not, at least knowing which error you're seeing would be handy.)

That should give you the full traceback, and thus a bit more info about what's going wrong.

**Comment by starsnabove** [comment] 2015-02-26 01:06
I found it coming from tutorlib/gui/app/app.py line 574. but putting raise in there is not going to the terminal for some reason, nor are any prints. It is the only location that I can find with that string with grepping (which is not easy under windows).

**Comment by starsnabove** [comment] 2015-02-26 01:16
which the exception there is the `WebAPIError` raised on line 121 of `tutorlib/interface/web_api.py`
Which is caused by the attempt to login using the default username and password of `None`

**Comment by sapi** [comment] 2015-02-26 01:21
I really need the traceback, unfortunately.  I keep nested tracebacks, and the root cause is going to be somewhere in `session.py`; the `WebAPIError` just wraps the underlying exception, so that the app itself only has to catch the one thing.

My understanding is that the only errors we should be expecting to see are errors with the connection itself (or errors in the cgi script, potentially).  `SessionManager.login` doesn't throw any exceptions itself (again, except to wrap errors).

Is there any chance you could try running mpt through PowerShell?  At least on Windows 7, that gives me the tracebacks when I insert a `raise`.  PowerShell even supports `cd` for getting to the right directory! :P 

Something like `C:\Python34\python.exe MyPyTutor.py` from the MPT directory should do it.

**Comment by starsnabove** [comment] 2015-02-26 01:22
I have been in command line but will try powershell

**Comment by starsnabove** [comment] 2015-02-26 01:25
This is what have done in the login method in api.py

        try:
            logged_in = self.web_api.login()
        except WebAPIError:
            print("blah")
            raise
            tkmessagebox.showerror(
                'Login failed',
                'Please check your credentials and try again.  ' \
                'If the problem persists, check your internet connection.  ' \
                'Some functionality (such as submitting answers) will be ' \
                'unavailable until you log in successfully.'
            )

and even in powershell nothing is going out to terminal

**Comment by sapi** [comment] 2015-02-26 01:36
What happens if you remove the `try`/`except` statement entirely (just run `self.web_api.login()` and let it throw)?

Do you get a traceback printed to the console then?

**Comment by starsnabove** [comment] 2015-02-26 01:39
not thinking straight - should have thought of that

C:\Users\Starsnabove\Documents\mpt>python.exe MyPyTutor.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\online\session.py", line 171
, in _open
    return self._opener.open(url, data)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 501, in error
    result = self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 501, in error
    result = self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python34\lib\urllib\request.py", line 463, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 481, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python34\lib\urllib\request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certifica
te verify failed (_ssl.c:600)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\interface\web_api.py", line
121, in login
    success = self.session_manager.login(username, password)
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\online\session.py", line 97,
 in login
    response = self._open(url)
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\online\session.py", line 178
, in _open
    ) from e
tutorlib.online.exceptions.RequestError: Connection Error.  Check your network c
onnection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 582, in callit
    func(*args)
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\gui\app\app.py", line 574, i
n login
    logged_in = self.web_api.login()
  File "C:\Users\Starsnabove\Documents\mpt\tutorlib\interface\web_api.py", line
126, in login
    ) from e
tutorlib.interface.web_api.WebAPIError

**Comment by starsnabove** [comment] 2015-02-26 01:39
It has a connection error in there but I am connected to the net

**Comment by sapi** [comment] 2015-02-26 01:40
The underlying error appears to be a SSL verification error.

My guess is that the requests module on Windows 8 doesn't trust self-signed certificates by default.

**Comment by starsnabove** [comment] 2015-02-26 01:41
I always knew Windows had trust issues

**Comment by sapi** [comment] 2015-02-26 01:56
I find it interesting that only Windows throws the exception, actually.

@jgat Thoughts on how you'd like us to handle this?

One option seems to be to create a `urllib.requests.HTTPSHandler` with a ssl context which has disabled verification, and pass that to `build_opener`.
Alternatively, we could probably download the public certificate we're using for the server and explicitly include that in the trusted certificate chain.

**Comment by starsnabove** [comment] 2015-02-26 01:58
Its only windows 8 that's doing it too so unless there is something in 8
that is causing the problem

**Comment by sapi** [comment] 2015-03-02 00:57
Updates verified in the lab today.

**Closed by sapi** 2015-03-02 00:57 UTC
Labels: help wanted
