### ISSUE TITLE
Login Fails on OSX

### ISSUE THREAD

**Issue by athleticus** [CSSE1001/MyPyTutor#129] opened 2015-02-27 05:42 UTC
Initial login fails:
```
python3 code/MyPyTutor.py
Checking for MyPyTutor updates...done
Creating default config...done
Downloading default tutorial package...done
Installing default tutorial package...done
Checking for tutorial package updates...done

Please enter your UQ username and password
Username: uqbmart8
Password:

Attempting to login as uqbmart8...failed
```

After this, the main gui appears. If I attempt to login, I get the following (after pressing the enter key with the password box focused):
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tkinter/__init__.py", line 1533, in __call__
    return self.func(*args)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/gui/dialogs/login.py", line 73, in ok
    success = self.callback(user, password)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/session.py", line 150, in submit_login
    set_details(text3)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/session.py", line 102, in set_details
    self._user = json.loads(strip_header(text))
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/parser.py", line 19, in strip_header
    if len(text) > len(MPT_HEADER)+3 else text))
tutorlib.online.exceptions.BadResponse: Invalid response from server: '<!DOCTYPE ht...'
```

Subsequent attempts yield:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/session.py", line 171, in _open
    return self._opener.open(url, data)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tkinter/__init__.py", line 1533, in __call__
    return self.func(*args)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/gui/dialogs/login.py", line 73, in ok
    success = self.callback(user, password)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/session.py", line 148, in submit_login
    response3 = self._open(form_url, form_data)
  File "/path/to/CSSE1001/MyPyTutor/code/tutorlib/online/session.py", line 178, in _open
    ) from e
tutorlib.online.exceptions.RequestError: Connection Error.  Check your network connection and try again.
```

**Comment by athleticus** [comment] 2015-02-27 05:48
After this, if I cancel this dialog, go to a problem and then choose Online->Login it tells me that I am already logged in as uqbmart8. If I repeat this process using an incorrect password in the dialog box, I am instead prompted that I have entered an incorrect username/password.

**Comment by sapi** [comment] 2015-02-27 05:50
Do you get a popup when you launch MPT telling you about the failure?

Trying to work out if this is similar to an elusive issue I see every now
and then.

**Comment by athleticus** [comment] 2015-02-27 05:51
No, I don't get any such popup.

**Comment by athleticus** [comment] 2015-02-27 05:51
How does one reset the choice to use keyring? Even though I delete my config file when trying to login again, I am no longer prompted to use that as I was initially.

**Comment by sapi** [comment] 2015-02-27 06:02
You won't get promoted to install it again, because it's already installed.
You should get promoted for the username and password again after clearing
the config file, though.

**Comment by sapi** [comment] 2015-02-27 07:37
Verified issue on OS X, but with a slight caveat: Online -> Logout followed by Online -> Login authenticated me without the need to even enter a password.

Not sure what's going on here.  The `web_api` argument to `TutorialApp` should be either `None` or logged in; there's even an assertion enforcing that!

My best guess (only a guess at the moment) is that we might be timing out on the client (due to the `socket` timeout), but then have the server get around to logging us in, causing further attempts to fail.  That would be...irritating...if it were the case.  A longer timeout would probably fix it for all practical cases, however.

**Comment by pjritee** [comment] 2015-02-28 20:45
I get the same on LInux (this is after installing, shutting down and starting up again - the same thing happens at install time):

$ python3 MyPyTutor.py 
Checking for MyPyTutor updates...done
Checking for tutorial package updates...done
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1490, in __call__
    return self.func(*args)
  File "/home/pjr/MyPyTutor/tutorlib/gui/dialogs/login.py", line 73, in ok
    success = self.callback(user, password)
  File "/home/pjr/MyPyTutor/tutorlib/online/session.py", line 150, in submit_login
    set_details(text3)
  File "/home/pjr/MyPyTutor/tutorlib/online/session.py", line 102, in set_details
    self._user = json.loads(strip_header(text))
  File "/home/pjr/MyPyTutor/tutorlib/online/parser.py", line 19, in strip_header
    if len(text) > len(MPT_HEADER)+3 else text))
tutorlib.online.exceptions.BadResponse: Invalid response from server: '<!DOCTYPE ht...'

**Comment by sapi** [comment] 2015-02-28 22:28
I modified `strip_header` to no longer clip the response, so that we can see the full error page.

@pjritee @athleticus If this is reproducable for you, could you please cause the error again, and include the full exception (which should now have the complete HTML)?

**Comment by pjritee** [comment] 2015-02-28 22:40
$ python3 MyPyTutor.py 
Default MyPyTutor install directory: /home/pjr/MyPyTutor
Type 'yes' if you would like to change the install directory: 
Installing MyPyTutor...done
Checking for MyPyTutor updates...done
Downloading default tutorial package...done
Installing default tutorial package...done
Checking for tutorial package updates...done
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1490, in __call__
    return self.func(*args)
  File "/home/pjr/MyPyTutor/tutorlib/gui/dialogs/login.py", line 73, in ok
    success = self.callback(user, password)
  File "/home/pjr/MyPyTutor/tutorlib/online/session.py", line 150, in submit_login
    set_details(text3)
  File "/home/pjr/MyPyTutor/tutorlib/online/session.py", line 102, in set_details
    self._user = json.loads(strip_header(text))
  File "/home/pjr/MyPyTutor/tutorlib/online/parser.py", line 17, in strip_header
    raise BadResponse("Invalid response from server: {!r}".format(text))
tutorlib.online.exceptions.BadResponse: Invalid response from server: '<!DOCTYPE html>\n<html>\n    <head>\n        <title>MyPyTutor</title>\n    </head>\n    <body>\n        <p>Unknown action: userinfo?action=userinfo</p>\n    </body>\n</html>\n'

**Comment by sapi** [comment] 2015-03-01 00:24
Not sure what's going on here.  @jgat, I think I'm going to need your help on this one.

Quick recap:
* all login attempts are failing
  * tested on `new_installer`, with `keyring` installed (so auto login)
  * also present on `master`
* authentication seems to work, as we're getting redirected to `mpt_cgi.py` at the appropriate step (`text3` in the client code)
* the redirection fails, as the `action` key is invalid (see below)

Somehow we're ending up with a form which looks something like:

    {'action': 'userinfo?action=userinfo'}

In other words, it's almost like a weird repetition of the query params (but in the form).

It doesn't look like the behaviour you'd expect for a duplicated value in `cgi.FieldStorage`, though; [the documentation](https://docs.python.org/3/library/cgi.html) indicates that that should be a list (and so should not concatenate in the `HTML_ERROR.format` call).

The actual URL printed in `uqauth.redirect` looks ok, though.  It prints out:

    Location: https://api.uqcloud.net/login/http://csse1001.uqcloud.net/cgi-bin/mpt3/mpt_cgi.py?action=userinfo

As far as I can tell that should be fine.  Reading the wiki, the only stage we're really involved in is the redirect, so if that's playing nice I'm not sure what's up.

**Comment by pjritee** [comment] 2015-03-01 00:44
Does this look like something we should contact the systems guys about?

**Comment by sapi** [comment] 2015-03-01 00:51
A hotfix to this error is possible, but I don't really want to band-aid over the problem without understanding why it occurred.

At the moment, we have:

    action = form['action'].value
    if action not in ACTIONS:
        print HTML_ERROR.format("Unknown action: " + action)
        return

We could alter that to explicitly deal with the duplicated set of query params:

    action = form['action'].value
    action = action.split('?')[0]  # band-aid - take component before query params
    if action not in ACTIONS:
        print HTML_ERROR.format("Unknown action: " + action)
        return

I applied that hotfix on the server briefly, and it permitted us to login.  I logged all requests to a file in `/tmp`, and the only one that was messed up was the initial redirection, so I think it must have something to do with SSO.

**Comment by jgat** [comment] 2015-03-01 00:52
This is possibly something that someone in ITIG (probably @arekinath) should look at: https://api.uqcloud.net/login/http://csse1001.uqcloud.net/cgi-bin/mpt3/mpt_cgi.py?action=userinfo should redirect to `mpt_cgi.py?action=userinfo`, but actually redirects to `mpt_cgi.py?action=userinfo?action=userinfo`.

We might be able to "fix it" by replacing all GET requests with POSTs, if those are still working.

**Comment by sapi** [comment] 2015-03-01 00:52
I reverted to an old commit briefly (af27d81), and the error is also present in that, which makes me think it's not on our end.

@pjritee I think it would be worth asking if anything has changed with the SSO system, as it doesn't look like it's a problem on our end.  At least we do have the option of a hotfix if we can't track down what's actually changed in time.

**Comment by pjritee** [comment] 2015-03-01 00:58
Are you able to do that yourself (i.e. ask) or do you need me to do it?

**Comment by jgat** [comment] 2015-03-01 01:01
Because I wrote "@arekinath" in my comment above, Alex will probably start getting emails about every reply in this thread from that point onwards. But you could still open a helpdesk ticket to make sure.

**Comment by pjritee** [comment] 2015-03-01 01:27
I put in a helpdesk request saying Alex should be getting emails about the problem. Can more detailed info be posted here to help Alex out

**Comment by jgat** [comment] 2015-03-01 01:28
This comment: https://github.com/CSSE1001/MyPyTutor/issues/129#issuecomment-76561608 should contain the relevant info.

**Comment by arekinath** [comment] 2015-03-01 05:06
So this would have started happening on the 28th, when we cleaned up a bunch of static server blocks in the load balancer configuration. One of the blocks cleaned up was the one for `csse1001.zones`, which is now using the default case common to all zones rather than its own individual block.

The only difference is that now the load balancers intercept and handle the `/_set_cookie/` paths instead of passing it through to your zone. And there was a typo (a missing `?`) in the handler for these, causing the duplicated query strings. Looks like it's been there a while, but very few people use query strings in their auth redirects so nobody noticed. :|

Should be all fixed now, sorry for the mess-up at an important time of the year.

**Comment by sapi** [comment] 2015-03-01 05:13
Thanks Alex.  Confirmed as fixed on our end.

I'm closing this issue to keep things self-contained.  There are still sporadic network problems, but we should raise them in separate issues as they come up.

**Closed by sapi** 2015-03-01 05:13 UTC
Labels: bug
